### ISSUE TITLE
Distribution of Passwords in an Arrowhead Cloud

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-arrowhead/roadmap#25]
Hello,

currently I try to handle passwords for external (legacy) systems. For example I want to use an MQTT-Broker with Username and Password authentication. The problem here is that I don't want to store the credentials in the source code or applications.properties. Therefore I searched for a software system/framework to store/retrieve credentials for my applications and I found the software [Hashicorp Vault](https://www.vaultproject.io/). It has an open api to access the stored secrets and a spring framework integration for [cloud](https://github.com/eclipse-arrowhead/roadmap/issues/18) and client.

KR,
BlackRose01

**Comment by emanuelpalm** [comment]
@BlackRose01 I would assume something like the [Configuration Manager](https://github.com/eclipse-arrowhead/core-java-spring/pull/318) would not be what you want?

The Arrowhead way is to use certificates as far as possible rather than passwords. If you have legacy systems that need to store passwords I assume Vault could be a suitable choice.

**Comment by BlackRose01** [comment]
Thank you for the answer. Yeah, the Configuration Manager is not the suitable solution for the problem and I will implement Vault. Thank you.
