### ISSUE TITLE
Release Template

### ISSUE THREAD

**Issue by tsvetlin** [eclipse-arrowhead/roadmap#39]
This issue aims to provide a template for future Arrowhead releases, in a unified clear format.

I've looked at other projects for inspiration regarding a template.
[Visual Studio Code](https://github.com/microsoft/vscode/releases)
[Eclipse Che](https://github.com/eclipse/che/releases)
[Eclispe Leshan](https://github.com/eclipse/leshan/releases)
[Eclipse Ditto](https://github.com/eclipse/ditto/releases)

My proposal is the following:

Title: Arrowhead X.Y.Z (semver 2.0 version number is X.Y.Z)

New Features:
 - list of new core systems, new featues
 eg.: * Pland Description Enginge:
 	new core system and a brief description about what is does

 Enhancements:
 - improvements to existing core systems with issues linked

 Bugs fixed:
 - list of bugs fixed with issues linked

Closed issues:
 - resolved or dismissed, mainly questions by community

 Issue count tracker diagram???? (as can be seen in the VS Code's example) not sure about its usefulness
 
 Example Template:
 
#  Arrowhead 4.4.0

## New Features

- New Core System: Plant Description Engine
 Brief description of this core system
 - New Core System: Time Manager
 Brief description of this core system
 
## Enhancements:
- Use of ISO8601 time stamps https://github.com/eclipse-arrowhead/core-java-spring/issues/193
- Network address detection: https://github.com/eclipse-arrowhead/core-java-spring/issues/309

## Bugs fixed:
- Deprecated dependency of Translator https://github.com/eclipse-arrowhead/core-java-spring/issues/295

## Closed issues:
- Service Registry endpoint duplicates https://github.com/eclipse-arrowhead/core-java-spring/issues/346

## Uploaded files:
- Core System JAR files in a zip
- Documentation PDF-s in a zip

**Comment by emanuelpalm** [comment]
This relates to #23. @awoSYS, any comments?

**Comment by jenseliasson** [comment]
Hi.
I think it is an excellent proposal from Szvetlin.

Jens

**Comment by awoSYS** [comment]
This is great! Having this kind of notes for each release would imho be equal to a changelog, so no extra CHANGELOG.md needed (#23).

As per https://keepachangelog.com/en/1.0.0/, `added`, `changed`, `removed`, `deprecated` and `security` items should be included. I personally don't see a point in keeping them in separate sections. I think it's more helpful to have them all listed in one section, grouped by component (e.g. core system), so that it's easy to grasp what has changed about a particular core system. That section could be named just "changes and enhancements" or something and even include new components.

`fixed` and closed issues might go into separate sections, as I've seen this in other projects before.
