### ISSUE TITLE
GSoSD Review Discussion Tracking Issue

### ISSUE THREAD

**Issue by emanuelpalm** [eclipse-arrowhead/roadmap#63]
As part of #54, we decided on 10 discussion points that need to be resolved before we can proceed to release the GSoSD. Here, the issues related to those discussion points are listed such that we can monitor how those issues are progressing.

Issues whose names are not links have not yet been created, or not yet been added to this list.

1. #58
    - __Lead:__ Per Olofsson, Sinetiq
2. #66 
    - __Lead:__ Pal Varga, BME
    - __Related Issues:__ #59, #35.
3. #69
    - __Lead:__ Cristina Paniagua, LTU
    - __Related Issues:__ #4, #19.
4. #67
    - __Lead:__ Felix Laringa, University of Mondragon
5. #65 
    - __Lead:__ Jerker Delsing, LTU
    - __Related Issues:__ #55.
6. #64
    - __Lead:__ Per Olofsson, Sinetiq
7. #70 
    - __Lead:__ Olof Schelén, LTU
    - __Related Issues:__ #13, #9.
8. #68 
    - __Lead:__ Jerker Delsing, LTU
9. #62 
    - __Lead:__ Rajmund Bocsi, AITIA
10. #71 
    - __Lead:__ Jan van Deventer, LTU

**Comment by emanuelpalm** [comment]
My hope is that as we start to close the above 10 issues, we can close some of the related issues as well.

**Comment by jerkerdelsing** [comment]
Since we agreed on how to handle all of these points I now close this issues.
#1 Per to introduce into GSoSD - issue #58 - DONE but not merged yet
#2 Pal to add to GSoSD- issue # 66 - DONE in GSoSD
#3 communication - not urgent - issues #69 - to v5.1
#4 Felix to introduce into GSoSD - issue #67 - waiting for Felix
#5 Jerker to introduce into GSoSD - issue #65 - DONE in GSoSD
#6 Per to introduce into the GSoSD - issue #64 - DONE but not merged yet
#7 Jerker to introduce into GSoSD- issue #70 - DONE in GSoSD
#8 communication - branding - issues #68 - DONE in GSoSD
#9 Technology - issue #62 - DONE in GSoSD
#10 Technology - issue #71 - DONE in GSoSD
