### ISSUE TITLE
GSoSD Review Discussion Point 6: The Role of an Authentication System?

### ISSUE THREAD

**Issue by PerOlofsson-Sinetiq** [eclipse-arrowhead/roadmap#64]
The reason for extracting the Authentication from the Authorisation is primarily to keep unrelated functions in different packages. 

The Authentication function deals with the task of establishing a verified identity of a user or system. This operation typically occurs at the establishment of a session and will durate for a time. When expiring, the user/system should renew the  authentication. The duration might depend on the classification of data, which is out of scope of the authentication, but should be configurable in the service.

There are different ways of establishing the Authentication, for example a username/password, 2-phase login, biometrics or mechanical tags such as RFID. These methods should be interchangeable at a defined service interface to decouple the authentication from other functions such as authorisation.

Currently, there exists some implementations in the industry, such as Swedish BankID and Single-sign-on solutions from Microsoft. Implementations of an Authentication System can be related/tied to the implementation of Authorisation if the situation is preferred.

**Comment by emanuelpalm** [comment]
> The Authentication function deals with the task of establishing a verified identity of a user or system. 

Does it handle both users AND systems, or users OR systems? Do we have to separate the two?

In many deployments, users will already have identities via Bank-ID, Active Directory (AD), or some other systems. My suspicion is that systems will not have _a priori_ identities, and there will be no real opportunity to give them Bank-ID or AD identities. Does the authentication system deal with both users and systems in the same way, while leaving integration against existing user identity systems to some other system? Or will there be many different authentication systems that support different user authentication procedures? Can they all have the same basic service interface type, or will there have to be many of those as well?

**Comment by borditamas** [comment]
**AITIA view**

> The Authentication function deals with the task of establishing a verified identity of a user or system.

Basically there is no need for human user accounts to operate an arrowhead cloud. For the secure communication within an arrowhead cloud we only have to identify the systems, therefore an Authentication System should only deal with the systems (core, support, consumer, provider). If user level authentication is required in a use case, then it could be managed with an other support system.  

> The Role of an Authentication System?

We think that since the intention is to supoort not only the X.509 certificates, but also other solutions, then an Authentication system should be the only one who has the permission and role to give an identity to a system within a specific arrowhead local cloud. (For example the identity could be some type of certificate or token.)

**Comment by jerkerdelsing** [comment]
Seams there is a support for having both an Authentication and Authorisation system. Identification of a human user should be yet another system, yet to be concluded.

**Comment by PerOlofsson-Sinetiq** [comment]
Proposed solution:
There should be an Authentication System available in the core systems. The role of the Authentication System should be to provide and verify identity tokens to any system in the Arrowhead cloud.

**Comment by jerkerdelsing** [comment]
Per to update the GSoSD.
