### ISSUE TITLE
GSosD review discussion Point #8: What terms to use for Services and Systems? Microservices and microsystems?

### ISSUE THREAD

**Issue by jerkerdelsing** [eclipse-arrowhead/roadmap#68]
Historically we started of with the terms services and systems.
Since a few years this has in a lot of our communication changes to microservice and microsystems.
The argument behind has been:

- Microservices  (small services well documented with a limited number of interfaces and parameters) is similar to our cloud friends. Which can simplify cloud community to understand and see the benefit of integration and interoperability from edge to cloud.
- Microsystems (small self contained system/thing/functionality) enabling simplified validation and verification. Microsystems always interact with the surrounding word through well documented services.

For the system word there are multiple communities using it for a wide range of meanings. Limiting us to fewer communities will most likely help our communication and marketing of Eclipse Arrowhead as "The edge microservice" architecture and technology.

For the term services there again are multiple communities using it for various meanings. Limiting our self to microservice will reduce the number of communities to interact, compete and comply with. Again this is in support of our communication and marketing  of Eclipse Arrowhead as "The edge microservice" architecture and technology.

**Comment by emanuelpalm** [comment]
I think the idea of Arrowhead as _microservices for the edge_ sounds like an excellent branding strategy. Calling Arrowhead that does not force us to use the term "microservice" every time we refer to a service, however. As far as I understand it, even people who work with microservices often refer to them as "just" services.

What I really see as the problem, however, is the term _system_. A system can be almost anything, but in the communities we are moving around I understand term tends to most commonly refer to a _distributed system_. I don't really see how prefixing "system" with "micro" avoids this confusion.

**Comment by DavidRutqvist** [comment]
I agree that marketing Arrowhead as an Edge alternative is beneficial. However, I disagree with the usage of "microservice" and "microsystems" terms as defined above simply because they are not properly aligned with the industry norm. While there is no clear definition about what constitutes a microservice, speaking from experience working in and discussing with other engineers working in very large microservice architecture organizations, the common understanding would be something as follows.

A microservice is a fine-grained, self-contained system/process/executable/binary that fulfils a single purpose, typically modelled around a business function and hosted independently from other microservices. It can fulfil its purpose by, for example, calling other microservices. All interactions between microservices are done over well-defined interfaces often referred to as APIs. It is not uncommon for a microservice to provide multiple interfaces (APIs) for the same domain object, e.g. one REST API and one event-driven API (async API). Remember that the microservice architecture is heavily influenced by domain-driven design together with the learnings from the early SOA hype.

Referring to the Arrowhead concept reference, a service is defined as "a set of operations provided by a system for other systems to consume" and a system is defined as "a software instance able to exercise capabilities of its hosting device". Applying this to the discussion, it implies that a microservice is a system and APIs are services.

This presents two somewhat conflicting definitions:
- The system/service concept from the concept document.
- The industry's understanding of microservices.

We should choose one definition. I suggest updating the first definition to emphasize the integration between systems using services as such:
- a service is defined as a set of operations provided by a system for other systems to consume. An API is an equal term to service.
- a system is an entity that can provide and consume services.

The exact wording is up for discussion but the importance being that information is exchanged over well-defined services that belong to a system and integration can only be done via services. he interpretation of a system depends on perspective and implementation knowledge. So, the term "system" shouldn't be tied to deployment specifics, dropping "software instance." Consequently, we could simplify by only using "system" instead of "system-of-systems."

Also, for a similar discussion in another project, refer to this issue: https://github.com/backstage/backstage/issues/390.

**Comment by jerkerdelsing** [comment]
Arrowhead is Microservices at the edge.. Jerker will address this in the GSoSD

**Comment by jerkerdelsing** [comment]
Addressed in the GSoSD
